/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AppealBattleIdRouteImport } from './routes/appeal.$battleId'
import { Route as BattleBattleIdRouteImport } from './routes/battle.$battleId'
import { Route as ResultsBattleIdRouteImport } from './routes/results.$battleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealBattleIdRoute = AppealBattleIdRouteImport.update({
  id: '/appeal/$battleId',
  path: '/appeal/$battleId',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleBattleIdRoute = BattleBattleIdRouteImport.update({
  id: '/battle/$battleId',
  path: '/battle/$battleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsBattleIdRoute = ResultsBattleIdRouteImport.update({
  id: '/results/$battleId',
  path: '/results/$battleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/appeal/$battleId': typeof AppealBattleIdRoute
  '/battle/$battleId': typeof BattleBattleIdRoute
  '/results/$battleId': typeof ResultsBattleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/appeal/$battleId': typeof AppealBattleIdRoute
  '/battle/$battleId': typeof BattleBattleIdRoute
  '/results/$battleId': typeof ResultsBattleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/appeal/$battleId': typeof AppealBattleIdRoute
  '/battle/$battleId': typeof BattleBattleIdRoute
  '/results/$battleId': typeof ResultsBattleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/appeal/$battleId'
    | '/battle/$battleId'
    | '/results/$battleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/appeal/$battleId'
    | '/battle/$battleId'
    | '/results/$battleId'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/appeal/$battleId'
    | '/battle/$battleId'
    | '/results/$battleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  AppealBattleIdRoute: typeof AppealBattleIdRoute
  BattleBattleIdRoute: typeof BattleBattleIdRoute
  ResultsBattleIdRoute: typeof ResultsBattleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/$battleId': {
      id: '/appeal/$battleId'
      path: '/appeal/$battleId'
      fullPath: '/appeal/$battleId'
      preLoaderRoute: typeof AppealBattleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$battleId': {
      id: '/battle/$battleId'
      path: '/battle/$battleId'
      fullPath: '/battle/$battleId'
      preLoaderRoute: typeof BattleBattleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$battleId': {
      id: '/results/$battleId'
      path: '/results/$battleId'
      fullPath: '/results/$battleId'
      preLoaderRoute: typeof ResultsBattleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  AppealBattleIdRoute: AppealBattleIdRoute,
  BattleBattleIdRoute: BattleBattleIdRoute,
  ResultsBattleIdRoute: ResultsBattleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
